[general]
version = "3.1.1"
language = "en"
createdAt = "2026-05-25T14:26:27.489Z"

[routing]
mode = "smart"

[routing.frontend]
models = [ "codex" ]
primary = "codex"
strategy = "fallback"

[routing.backend]
models = [ "codex" ]
primary = "codex"
strategy = "fallback"

[routing.review]
models = [ "codex" ]
strategy = "fallback"

[workflows]
installed = [ "go", "init-project", "context", "commit", "rollback", "clean-branches", "worktree", "spec-init", "spec-research", "spec-plan", "spec-impl", "spec-review" ]

[paths]
commands = "/home/coringawc/.config/opencode/ccg/commands/ccg"
prompts = "/home/coringawc/.config/opencode/ccg/.ccg/prompts"
backup = "/home/coringawc/.config/opencode/ccg/.ccg/backup"

[mcp]
provider = "skip"
setup_url = "https://augmentcode.com/"

[performance]
liteMode = false
skipImpeccable = false
